using UnityEngine;

namespace Project.Runtime.Combat
{
    public class RagdollController : MonoBehaviour
    {
        [Header("COMPONENT REFERENCES")]
        [SerializeField] private Animator animator;

        private Rigidbody[] _rigidbodies;
        private Collider[] _colliders;

        private void Awake()
        {
            // AUTO DETECT ANIMATOR ON THIS OBJECT IF UNASSIGNED
            if (animator == null)
            {
                animator = GetComponent<Animator>();
            }

            // COLLECT ALL BONE RIGIDBODIES AND COLLIDERS GENERATED BY RAGDOLL WIZARD
            _rigidbodies = GetComponentsInChildren<Rigidbody>();
            _colliders = GetComponentsInChildren<Collider>();

            // LOCK PHYSICS SO ANIMATION CONTROLS THE SKELETON INITIALLY
            SetRagdollActive(false);
        }

        public void SetRagdollActive(bool active)
        {
            // TOGGLE ANIMATOR TO PREVENT FIGHTING RIGIDBODIES
            if (animator != null)
            {
                animator.enabled = !active;
            }

            // RIGIDBODIES GO DYNAMIC ONLY ON DEATH
            foreach (Rigidbody rb in _rigidbodies)
            {
                rb.isKinematic = !active;
                rb.useGravity = active;
            }

            // COLLIDERS STAY ACTIVE AT ALL TIMES SO RAYCASTS ALWAYS DETECT BONES
            foreach (Collider col in _colliders)
            {
                col.enabled = true;
            }
        }

        public void TriggerRagdoll(Collider hitCollider, Vector3 forceDirection, float forceMagnitude)
        {
            // ACTIVATE PHYSICS ACROSS ALL BONES
            SetRagdollActive(true);

            // DETACH OBJECT FROM BIKE OR ROOT SO IT TUMBLE FREELY IN WORLD
            transform.SetParent(null);

            // FIND RIGIDBODY ASSOCIATED WITH THE STRUCK COLLIDER
            Rigidbody targetBoneRb = null;
            if (hitCollider != null)
            {
                targetBoneRb = hitCollider.attachedRigidbody;
            }

            // FALLBACK TO FIRST BONE IF SPECIFIC HIT RIGIDBODY IS MISSING
            if (targetBoneRb == null && _rigidbodies.Length > 0)
            {
                targetBoneRb = _rigidbodies[0];
            }

            // APPLY LOCALIZED IMPULSE DIRECTLY TO THE IMPACTED BONE
            if (targetBoneRb != null)
            {
                targetBoneRb.AddForce(forceDirection * forceMagnitude, ForceMode.Impulse);
            }
        }
    }
}